doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Domain/Model'
                prefix: 'App\User\Domain\Model'
                alias: User
            ProductCatalog:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/ProductCatalog/Domain/Model'
                prefix: 'App\ProductCatalog\Domain\Model'
                alias: Product
            ShoppingCart:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/ShoppingCart/Domain/Model'
                prefix: 'App\ShoppingCart\Domain\Model'
                alias: Product