parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ###Configuration for Shared
    App\Shared\:
        resource: '../src/Shared'
        exclude: '../src/Shared/Domain/{ValueObject}'
    ###End of configuration for Shared

    ###Configuration for User use case
    App\User\Domain\:
        resource: '../src/User/Domain'
        exclude: '../src/User/Domain/{Model}'

    App\User\Infrastructure\:
        resource: '../src/User/Infrastructure'
    ###End of configuration for User use case
