parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ###Configuration for Shared
    App\Shared\:
        resource: '../src/Shared'
        exclude: '../src/Shared/Domain/{ValueObject}'
    ###End of configuration for Shared

    ###Configuration for User use case
    App\User\Application\:
        resource: '../src/User/Application'

    App\User\Domain\:
        resource: '../src/User/Domain'
        exclude: '../src/User/Domain/{Model}'

    App\User\Infrastructure\:
        resource: '../src/User/Infrastructure'

    App\User\Ui\:
        resource: '../src/User/Ui'

    App\User\Ui\Api\:
        resource: '../src/User/Ui/Api'
        tags: ['controller.service_arguments']

    #Restrict handlers per bus
    App\User\Application\MessageHandler\Command\:
        resource: '%kernel.project_dir%/src/User/Application/MessageHandler/Command'
        tags:
            - { name: messenger.message_handler, bus: command.bus }
        autoconfigure: false
    ###End of configuration for User use case

    ###Configuration for ProductCatalog use case
    App\ProductCatalog\Application\:
        resource: '../src/ProductCatalog/Application'

    App\ProductCatalog\Domain\:
        resource: '../src/ProductCatalog/Domain'
        exclude: '../src/ProductCatalog/Domain/{Model}'

    App\ProductCatalog\Infrastructure\:
        resource: '../src/ProductCatalog/Infrastructure'

    App\ProductCatalog\Ui\:
        resource: '../src/ProductCatalog/Ui'

    App\ProductCatalog\Ui\Api\:
        resource: '../src/ProductCatalog/Ui/Api'
        tags: ['controller.service_arguments']

    #Restrict handlers per bus
    App\ProductCatalog\Application\MessageHandler\Command\:
        resource: '%kernel.project_dir%/src/ProductCatalog/Application/MessageHandler/Command'
        tags:
            - { name: messenger.message_handler, bus: command.bus }
        autoconfigure: false

    App\ProductCatalog\Application\MessageHandler\Query\:
        resource: '%kernel.project_dir%/src/ProductCatalog/Application/MessageHandler/Query'
        tags:
            - { name: messenger.message_handler, bus: query.bus }
        autoconfigure: false
    ###End of configuration for ProductCatalog use case

    ###Configuration for ShoppingCart use case
    App\ShoppingCart\Application\:
        resource: '../src/ShoppingCart/Application'

    App\ShoppingCart\Domain\:
        resource: '../src/ShoppingCart/Domain'
        exclude: '../src/ShoppingCart/Domain/{Model}'

    App\ShoppingCart\Infrastructure\:
        resource: '../src/ShoppingCart/Infrastructure'

    App\ShoppingCart\Ui\:
        resource: '../src/ShoppingCart/Ui'

    App\ShoppingCart\Ui\Api\:
        resource: '../src/ShoppingCart/Ui/Api'
        tags: ['controller.service_arguments']

    #Restrict handlers per bus
    App\ShoppingCart\Application\MessageHandler\Command\:
        resource: '%kernel.project_dir%/src/ShoppingCart/Application/MessageHandler/Command'
        tags:
            - { name: messenger.message_handler, bus: command.bus }
        autoconfigure: false

    App\ShoppingCart\Application\MessageHandler\Query\:
        resource: '%kernel.project_dir%/src/ShoppingCart/Application/MessageHandler/Query'
        tags:
            - { name: messenger.message_handler, bus: query.bus }
        autoconfigure: false

    App\ShoppingCart\Application\MessageHandler\Event\:
        resource: '%kernel.project_dir%/src/ShoppingCart/Application/MessageHandler/Event'
        tags:
            - { name: messenger.message_handler, bus: event.bus }
        autoconfigure: false
    ###End of configuration for ShoppingCart use case
